### ISSUE TITLE
Transmuting self to mut self is UB

### ISSUE THREAD

**Issue by kpp** [MichaelBurge/nes-emulator#3]
https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/joystick.rs#L49

https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/ppu.rs#L493

https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/joystick.rs#L43
https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/joystick.rs#L49

**Comment by MichaelBurge** [comment]
Thanks for catching this. I've replaced these with a `Cell` in the `Joystick` struct

https://github.com/MichaelBurge/nes-emulator/commit/110fa57e6a7f2e72298312661855c4afd9b4a54c

That particular line in `ppu.rs` is okay, because `CpuPpuInterconnect` stores mutable pointers which that is turning into mutable references.

There is a related issue in that

https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/ppu.rs#L520

allows two mutable references to a `C6502` object to be live at the same time. But that is slightly different than what you have here.
