### ISSUE TITLE
Dereferencing Headless::joystick1 is UB

### ISSUE THREAD

**Issue by kpp** [MichaelBurge/nes-emulator#5]
https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/headless.rs#L117

https://doc.rust-lang.org/reference/behavior-considered-undefined.html : Dereferencing a null or dangling raw pointer.

Headless::joystick1/2 are initialized with:

```
impl Headless {
    fn command_load_rom(&mut self) {
        let mut record_tas = self.read_byte();
        let filename = self.read_length_string();
        let mut joystick1 = Box::new(Joystick::new());
        let mut joystick2 = Box::new(Joystick::new());
        self.joystick1 = &mut *joystick1;
        self.joystick2 = &mut *joystick2;
        ...
        // drop joystick1 joystick2
        // Headless::joystick1/2 are dangling pointers since joystick1 joystick2 are freed
    }
```

**Comment by MichaelBurge** [comment]
`joystick1` and `joystick2` aren't freed - their ownership is transferred to the `Nes` object created in the same function.

`nes.rs` even has this line:
https://github.com/MichaelBurge/nes-emulator/blob/0b9e321832360b93ed6fcd9d54bb3c3f11eca00a/src/nes.rs#L156

because even though the second controller isn't used, its ownership needs to be transferred to prevent the exact problem you describe.

**Comment by kpp** [comment]
Right
